name: Create next release by PR

on: push

jobs:

  release-trigger:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_config: .github/release.tagpr
    - run: bash -c "next=$(cat .github/NEXT_VERSION) ; next=$(bash .github/scripts/increment_version.sh -M $next) ; echo $next > .github/NEXT_VERSION"