name: Create next release by PR

on: push

jobs:

  release-trigger:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    - uses: Songmu/tagpr@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INPUT_config: .github/release.tagpr
    - run: chmod +x ./.github/scripts/increment_version.sh
    - run: |
        bash -c "\
        current=$(cat ./.github/NEXT_VERSION) ;\
        echo $current ;\
        next=$(sh .github/scripts/increment_version.sh -M $current) ;\
        echo $next ;\
        echo $next > .github/NEXT_VERSION \
        "